version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: accessible-weather-shelter-backend:local
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./:/app:ro
