name: CI/CD Pipeline - Node.js Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    

    steps:
   
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List repo files
        run: ls -la

      # 3. Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/accessible-weather-shelter-backend:latest ./backend

      # 4. Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # 5. Push Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/accessible-weather-shelter-backend:latest
